// <auto-generated />
namespace Democracy.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class statistics : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(statistics));
        
        string IMigrationMetadata.Id
        {
            get { return "201504182208079_statistics"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
